{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.jobsName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestrator.jobsLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "orchestrator.jobsSelectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
{{- end }}
